wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    code_path: code/train_dqn.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1661999054.106009
    t:
      1:
      - 1
      - 3
      - 55
      2:
      - 1
      - 3
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 35
      4: 3.7.0
      5: 0.13.2
      8:
      - 5
wandb_entity:
  desc: null
  value: quantumiracle
wandb_name:
  desc: null
  value: dqn0
wandb_project:
  desc: null
  value: ensemble_dqn
